import React from 'react';
const Home = () => {
    return <div className='container'>
        <h1>Home</h1>
        <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa tempor nec feugiat nisl. Cras ornare arcu dui vivamus arcu felis bibendum ut tristique. Feugiat scelerisque varius morbi enim nunc faucibus a pellentesque. Magna fringilla urna porttitor rhoncus dolor. Elementum sagittis vitae et leo duis ut. At elementum eu facilisis sed odio morbi quis commodo. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Congue quisque egestas diam in arcu cursus euismod. Cursus eget nunc scelerisque viverra mauris in aliquam sem fringilla. Et malesuada fames ac turpis egestas integer eget aliquet nibh. Diam maecenas sed enim ut sem viverra. In tellus integer feugiat scelerisque varius. Placerat vestibulum lectus mauris ultrices. Nisl nunc mi ipsum faucibus vitae aliquet. Velit dignissim sodales ut eu sem integer. Volutpat consequat mauris nunc congue. Consequat interdum varius sit amet. A scelerisque purus semper eget duis at.

Ornare massa eget egestas purus. Ultrices dui sapien eget mi proin sed libero enim. Cursus turpis massa tincidunt dui ut ornare lectus sit amet. At tempor commodo ullamcorper a lacus vestibulum sed arcu. Sagittis id consectetur purus ut faucibus pulvinar elementum integer. Diam quis enim lobortis scelerisque fermentum. Malesuada proin libero nunc consequat interdum varius sit amet mattis. Vel risus commodo viverra maecenas accumsan. Facilisi etiam dignissim diam quis enim. Cursus risus at ultrices mi tempus imperdiet. Urna id volutpat lacus laoreet non curabitur gravida arcu. Purus sit amet luctus venenatis lectus magna fringilla urna. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Tortor posuere ac ut consequat.

Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet consectetur. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. Sagittis eu volutpat odio facilisis mauris. Consequat ac felis donec et odio pellentesque diam. Porta lorem mollis aliquam ut. Nunc mi ipsum faucibus vitae. Eu scelerisque felis imperdiet proin fermentum leo vel. Fringilla urna porttitor rhoncus dolor purus non enim. Semper feugiat nibh sed pulvinar proin gravida hendrerit lectus. Blandit libero volutpat sed cras ornare arcu dui vivamus. Urna porttitor rhoncus dolor purus non. Mauris nunc congue nisi vitae suscipit. Vitae sapien pellentesque habitant morbi tristique senectus et. Potenti nullam ac tortor vitae purus faucibus ornare. Lorem ipsum dolor sit amet consectetur adipiscing. Elementum nibh tellus molestie nunc.

Ut lectus arcu bibendum at. Venenatis tellus in metus vulputate eu. At tellus at urna condimentum mattis. Sit amet facilisis magna etiam tempor orci eu. Enim sed faucibus turpis in eu mi bibendum neque egestas. Commodo sed egestas egestas fringilla phasellus faucibus. Sapien faucibus et molestie ac feugiat sed. Metus dictum at tempor commodo. Quam nulla porttitor massa id neque aliquam vestibulum morbi. Lobortis feugiat vivamus at augue eget. Velit euismod in pellentesque massa placerat duis ultricies lacus sed. Nunc sed id semper risus in hendrerit.

Duis tristique sollicitudin nibh sit. Leo integer malesuada nunc vel. Tellus mauris a diam maecenas sed. Maecenas sed enim ut sem viverra aliquet. Scelerisque eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Ligula ullamcorper malesuada proin libero nunc consequat. Adipiscing vitae proin sagittis nisl. Nunc aliquet bibendum enim facilisis gravida neque convallis a cras. Adipiscing commodo elit at imperdiet. Eget lorem dolor sed viverra. Feugiat sed lectus vestibulum mattis. Velit ut tortor pretium viverra suspendisse potenti nullam ac. Congue nisi vitae suscipit tellus mauris a diam maecenas. Vivamus arcu felis bibendum ut tristique. Neque ornare aenean euismod elementum nisi quis. Vulputate dignissim suspendisse in est ante in nibh. Tincidunt id aliquet risus feugiat in ante metus dictum. Ipsum suspendisse ultrices gravida dictum.
        </p>
    </div>;
}

export default Home;